### ISSUE TITLE
Duvidas para testar.

### ISSUE THREAD

**Issue by lucascruz** [ceferrari/simplex#1]
Como se dar a instalação do mesmo (...) e via composer?

**Comment by ceferrari** [comment]
Lucas, você pode encontrar ele funcionando em http://simplex.16mb.com.
Mas se desejar fazer a instalação a partir do código fonte, pode seguir este tutorial:
http://mnmtechconsulting.com/blog/setting-up-laravel-5-ubuntu-14-04-amazon-ec2

**Comment by lucascruz** [comment]
Carlos você hoje possui alguma regra de utilização deste trabalho?

**Comment by ceferrari** [comment]
Lucas, você pode usar a versão implementada dele, disponível no link que citei no comentário anterior, da forma que quiser. O código fonte você pode modificar e utilizar, desde que cite o autor (eu).

**Comment by lucascruz** [comment]
Tranquilo Chefe = )

Em 14 de maio de 2016 08:33, Carlos Eduardo Ferrari <
notifications@github.com> escreveu:

> Lucas, você pode usar a versão implementada dele, disponível no link que
> citei no comentário anterior, da forma que quiser. O código fonte você pode
> modificar e utilizar, desde que cite o autor (eu).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ceferrari/simplex/issues/1#issuecomment-219220648>
>



-- 
Atenciosamente


Lucas da Silva Cruz

**Comment by lucascruz** [comment]
Caro colega tive um pequeno contra tempo em instalar localmente.
Utilizei o XAMPP para abrigar localmente o serviço. So que uma vez configurado com todas os requisitos do Laravel. Ao acionar um espaço /public me deparo com a seguinte mensagem "Whoops, looks like something went wrong." . Se faz necessário configurar algo mais? Ou disponibilizar numa VM e uma opção melhor pra isso?

**Comment by ceferrari** [comment]
Lucas, o Laravel disponibiliza uma VM que já vem com tudo instalado. Chama Homestead. Dá uma pesquisada.

**Comment by lucascruz** [comment]
Valeu Chefia = )

**Comment by lucascruz** [comment]
Conseguir resolver rsrsrs.. Debug On percebi o problema... faltou renomear o .env.example para .env e gerei uma outra key como artisan.. Conseguir.. Desde já agradeço pela dica =)
